import { test, expect, type Page } from '@playwright/test'

async function installProbe(page: Page) {
  await page.addInitScript(() => {
    const create = AudioContext.prototype.createAnalyser
    AudioContext.prototype.createAnalyser = function () {
      const node = create.call(this)
      ;(window as unknown as { audioProbe: AnalyserNode }).audioProbe = node
      return node
    }
  })
}
async function audioRms(page: Page) {
  return page.evaluate(() => {
    const probe = (window as unknown as { audioProbe: AnalyserNode }).audioProbe
    const buffer = new Float32Array(probe.fftSize); probe.getFloatTimeDomainData(buffer)
    return Math.sqrt(buffer.reduce((sum, x) => sum + x * x, 0) / buffer.length)
  })
}
const rpm = async (page: Page) => Number((await page.locator('.dial-readout strong').innerText()).replaceAll(',', ''))

test('compact English catalog separates models from Custom settings', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Custom', exact: true })).toBeVisible()
  await expect(page.getByLabel('Starting point')).toHaveValue('inline4')
  await expect(page.getByLabel('Fixed RPM', { exact: true })).not.toBeChecked()
  expect(await page.locator('html').getAttribute('lang')).toBe('en')
  expect(await page.locator('body').innerText()).not.toMatch(/[А-Яа-яЁё]/)
  await expect(page.locator('canvas, footer')).toHaveCount(0)
  await expect(page.getByText('Export WAV', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Drive', { exact: true })).toHaveCount(0)
  await page.getByLabel('Displacement', { exact: true }).fill('3')
  await page.getByLabel('Search models').fill('yamaha')
  await page.getByRole('button', { name: 'YZF-R1', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Yamaha YZF-R1' })).toBeVisible()
  await expect(page.getByLabel('Starting point')).toHaveCount(0)
  await expect(page.getByLabel('Displacement', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Model data' })).toHaveAttribute('href', /yamaha/)
  await page.getByRole('button', { name: 'Custom', exact: true }).click()
  await expect(page.getByLabel('Displacement', { exact: true })).toHaveValue('3')
  await page.getByRole('button', { name: 'YZF-R1', exact: true }).click()
  await page.getByRole('button', { name: 'Edit as Custom' }).click()
  await expect(page.getByRole('heading', { name: 'Custom', exact: true })).toBeVisible()
  await expect(page.getByLabel('Firing intervals')).toHaveValue('crossplane')
  expect(errors).toEqual([])
})

test('Space works immediately after starting and audio remains audible on throttle release', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await installProbe(page); await page.goto('/')
  await page.getByRole('button', { name: 'Start engine' }).click()
  await expect(page.getByText('Running', { exact: true })).toBeVisible()
  await page.keyboard.down('Space')
  await expect(page.locator('.gas-pedal')).toHaveClass(/pressed/)
  await page.waitForTimeout(600)
  const high = await rpm(page); expect(high).toBeGreaterThan(2000)
  await page.keyboard.up('Space')
  await page.waitForTimeout(600)
  expect(await rpm(page)).toBeLessThan(high)
  expect(await audioRms(page)).toBeGreaterThan(0.001)
  await page.keyboard.down('Space')
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await expect(page.locator('.gas-pedal')).not.toHaveClass(/pressed/)
  await page.keyboard.up('Space')
  await page.getByRole('button', { name: 'Stop engine' }).click()
  await expect(page.getByText('Stopped', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('fixed RPM disables both Space and the on-screen pedal', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start engine' }).click()
  await page.getByLabel('Fixed RPM', { exact: true }).check()
  await page.getByLabel('Fixed RPM value').fill('4200')
  await page.waitForTimeout(200) // Playback rerenders must not overwrite an in-progress numeric edit.
  await expect(page.getByLabel('Fixed RPM value')).toHaveValue('4200')
  await page.getByLabel('Fixed RPM value').press('Tab')
  await expect(page.locator('.dial-readout strong')).toHaveText('4,200')
  await expect(page.locator('.gas-pedal')).toBeDisabled()
  await page.getByRole('heading', { name: 'Custom', exact: true }).click()
  await page.keyboard.down('Space')
  await page.waitForTimeout(350)
  await expect(page.locator('.gas-pedal')).not.toHaveClass(/pressed/)
  await expect(page.locator('.dial-readout strong')).toHaveText('4,200')
  await page.keyboard.up('Space')
  await page.getByLabel('Fixed RPM', { exact: true }).uncheck()
  await expect(page.locator('.gas-pedal')).toBeEnabled()
  await page.waitForTimeout(250)
  expect(await rpm(page)).toBeLessThan(4200)
})

test('saves Custom settings and produces a working share link', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/')
  await page.getByText('Exhaust', { exact: true }).click()
  await page.getByLabel('Primary pipe length').fill('1.2')
  await page.getByRole('button', { name: 'Save engine', exact: true }).click()
  await page.getByLabel('Engine name').fill('My test engine')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'My test engine', exact: true })).toBeVisible()
  await page.getByText('Exhaust', { exact: true }).click()
  await expect(page.getByLabel('Primary pipe length')).toHaveValue('1.2')
  await page.getByRole('button', { name: 'Share', exact: true }).click()
  await expect(page.locator('.toast')).toHaveText('Link copied')
  const link = await page.evaluate(() => navigator.clipboard.readText())
  await page.evaluate(() => localStorage.clear())
  await page.goto('about:blank')
  await page.goto(link)
  await expect(page.getByRole('heading', { name: 'Custom', exact: true })).toBeVisible()
  await page.getByText('Exhaust', { exact: true }).click()
  await expect(page.getByLabel('Primary pipe length')).toHaveValue('1.2')
})

test('desktop and phone layouts are compact and contain no overflow', async ({ page }) => {
  await page.goto('/')
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  const dimensions = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }))
  expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.viewport)
  await page.getByRole('button', { name: 'Start engine' }).click()
  await page.locator('.gas-pedal').scrollIntoViewIfNeeded()
  const box = await page.locator('.gas-pedal').boundingBox()
  if (!box) throw new Error('Missing pedal')
  await page.mouse.move(box.x + 30, box.y + 20); await page.mouse.down()
  await expect(page.locator('.gas-pedal')).toHaveClass(/pressed/)
  await page.mouse.up()
  await expect(page.locator('.gas-pedal')).not.toHaveClass(/pressed/)
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
})

test('arrow keys shift once per press, buttons work, and fixed RPM locks gears', async ({ page }) => {
  await page.goto('/')
  const gear = page.getByLabel('Current gear', { exact: true })
  await expect(gear).toHaveText('N')
  await page.getByRole('button', { name: 'Start engine' }).click()
  await page.keyboard.down('ArrowUp')
  await expect(gear).toHaveText('1')
  await page.waitForTimeout(220)
  await page.keyboard.down('ArrowUp') // Repeated keydown must not advance again.
  await expect(gear).toHaveText('1')
  await page.keyboard.up('ArrowUp')
  await page.keyboard.down('Space'); await page.waitForTimeout(650); await page.keyboard.up('Space')
  const before = await rpm(page)
  await page.keyboard.press('ArrowUp')
  await expect(gear).toHaveText('2')
  await page.waitForTimeout(200)
  expect(await rpm(page)).toBeLessThan(before * 0.8)
  await page.keyboard.press('ArrowDown')
  await expect(gear).toHaveText('1')
  await page.waitForTimeout(220)
  await page.getByRole('button', { name: 'Shift down', exact: true }).click()
  await expect(gear).toHaveText('N')
  await page.waitForTimeout(220)
  await page.getByRole('button', { name: 'Shift up', exact: true }).click()
  await expect(gear).toHaveText('1')
  await page.getByLabel('Fixed RPM', { exact: true }).check()
  await page.getByRole('heading', { name: 'Custom', exact: true }).click()
  await page.keyboard.press('ArrowUp'); await page.keyboard.press('ArrowDown')
  await expect(gear).toHaveText('1')
  await expect(page.getByRole('button', { name: 'Shift up', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Shift down', exact: true })).toBeDisabled()
  await page.getByLabel('Fixed RPM value').focus()
  await page.keyboard.press('ArrowUp')
  await expect(gear).toHaveText('1')
  await page.getByRole('button', { name: 'Stop engine' }).click()
  await expect(gear).toHaveText('N')
})
